### ISSUE TITLE
Invalid link

### ISSUE THREAD

**Issue by CNCME** [bluzDK/bluz-docs#1]
The link (https://github.com/bluzDK/bluz-beta/tree/master/gateway/photon-sketch-0.1.0) in bluz-docs/docs/tutorials/getting_started.md in the Gateway Shield Setup section is bad.

**Comment by remcohn** [comment]
The sketch is currently in closed beta. Link will open up once its released.

**Comment by eely22** [comment]
Section has been updated, link changed to appropriate one.
